### ISSUE TITLE
matrix multiplication (Question)

### ISSUE THREAD

**Issue by asvolans** [jtablesaw/tablesaw#1129]
Does the library support multiplying two tables as matrix multiplication?

**Comment by lwhite1** [comment]
No it doesn’t.

**Comment by PeteSahad** [comment]
this would be really helpful.

I'm also currently looking for an easy way to do a python-style (a ** b) operation with two tables. Couldn't find anything though.

I actually thought this would be some basic stuff!?

**Comment by lwhite1** [comment]
>
> I actually thought this would be some basic stuff!?


You can convert a table to a double[][] using
tech.tablesaw.conversion.TableConverter. You can probably multiply the
results using Apache Math (which is already a tablesaw dependency), so it
is pretty basic stuff. I would say make a PR, but it's probably not worth
bringing into the library unless a number of matrix operations were
included. Even then, since it's just two-ish steps to export and run a
third-party library, I don't know that it's worth while

**Comment by PeteSahad** [comment]
Essentially you're right. I just thought, having such a nice and powerful library, it would be very convinient just doing these kind of operations with the actual tables.
But python really spoils you there. I'm just happy tablesaw exists :).

**Comment by lwhite1** [comment]
closing
