### ISSUE TITLE
Document Kotlin API

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#127]
I'm curious about the Kotlin API. What are the use cases? What's nicer about it? How do I use it?

**Comment by lwhite1** [comment]
When I started tablesaw years ago, it was intended to be used with the Java 9 REPL that was thought to be just around the corner. After several years of delay it's finally close to being real. 

REPLs are commonly used in Python and R by people doing data science because it fits well with the inherently interactive nature of exploratory data analysis.  Moreover, it can be very helpful in educational settings. Finally, you need a REPL to be used in Jupyter and most other notebooks. 

Kotlin has a nice REPL today. Better still, it's simpler syntax makes it more REPL-friendly than Java. Less boilerplate keeps the code more readable for people who may lack CS backgrounds or may have already some exposure to Python or R. Finally, Kotlin is not an ideal language for data analytics but it is closer than Java. It's (unfortunately limited) operator overloading being very attractive for example for expressing vector operations like ColumnA + ColumnB.
