### ISSUE TITLE
CSV file loading has become slow and is using too much memory

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#136]
I can no longer load a CSV file from the NYC taxi dataset (~1.9GB) on my laptop. 

Slowness may be a function of memory thrashing rather than a separate issue.  Check to see if it's loading doubles instead of floats for floating point numbers

**Comment by benmccann** [comment]
You're talking about this dataset? http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml

Which months do you use? Just a single month or multiple?

Do you run with any Xmx args?

**Comment by lwhite1** [comment]
yellow cab january 2016 with -Xmx10G.

**Comment by benmccann** [comment]
I ran `Taxi.java` with those args

On the old code:
>loaded 10906858 records in 94 seconds

On the new code I'm getting tired of waiting for it to finish and had to kill it.

**Comment by lwhite1** [comment]
seems about right. now just have to figure out what's different

**Comment by benmccann** [comment]
My guess would be this commit: https://github.com/jtablesaw/tablesaw/commit/630c40cc578ca8ab8fd95a6ab84d580650e8ef52

Before it was reading the file twice. Once to figure out column type and once to load the contents into the dataframe. I changed it to only read from the source once and store the data in memory because many sources you can't read multiple times. E.g. if you have a stream from over the network.

I'm not yet sure what the solution is though...

**Comment by benmccann** [comment]
Every cell of the CSV is being converted to a string in both the before and after cases. I guess that the big difference is whether we do it all before loading it into the table (current case) or as we load it into the table (previously)

**Comment by lwhite1** [comment]
Keeping the strings around increases the required memory by 5x or more.
Roughly. Depends on type, but it's probably more than we can get away with

**Comment by benmccann** [comment]
Ok, this should be fixed now. It reads just as fast as before, but still lets you fetch CSVs over the network with column type detection. Let me know if it's working for you now or not

**Comment by lwhite1** [comment]
Better than ever. Thanks so much.
