### ISSUE TITLE
Feature Request > iterator method on Column class

### ISSUE THREAD

**Issue by adriens** [jtablesaw/tablesaw#183]
Use Case

you have extracted a Column object and you want to fetch it for any purpose .

```java
// get the column and keep unique items only
Column regions = table.column(0).unique();
// sort them to display them in a nice sorted way
regions.sortAscending();
// now i want to iterate over them to feed..for example a file
// for now, i should fetch on item row of the column, on each index, until the last row
System.out.println(regions.getString(0));
System.out.println(regions.getString(1));
//... do this in a loop
```

What could be convinient would to have an iterator() method like this :

```java
Iterator<String> regionsIter = regions.iterator();
```

Wouldn't it be convenient ?...or did i miss somthing crucial in the current API ?
```

**Comment by lwhite1** [comment]
It depends on the goal. Category columns implement Iterable<String> because you generally want a string, but if you implement Iterable<Integer> for an int column, it will autobox all the values from ints into Integer objects, greatly increasing your memory usage. 

You can use an IntIterator instead: 

```
 IntIterator intIterator = iterator();
 while (intIterator.hasNext()) {
        int next = intIterator.nextInt();
        }

```

The columns should really all implement IntIterable or FloatIterable as appropriate, but some column types seem to be missing their variation.

**Comment by adriens** [comment]
Great, thanks a lot, i saw that, but i was not sure it was the good way !
