### ISSUE TITLE
Support Parquet Read/Write

### ISSUE THREAD

**Issue by yuj** [jtablesaw/tablesaw#221]
Should tablesaw support the more and more popular Parquet format?

**Comment by benmccann** [comment]
The main thing I'd want to be careful of is whether it can be done without adding too many transitive dependencies

**Comment by lwhite1** [comment]
reopening, for when a csv file is just not what you want.

**Comment by dclong** [comment]
Support Parquet format is a must.

**Comment by ccleva** [comment]
Hello,
I started working on a parquet reader/writer for tablesaw. @benmccann, @lwhite1, has a decision been made regarding whether to add new formats as sub-projects or use separate repositories (as discussed in #724) ?
Thanks

**Comment by lwhite1** [comment]
closing

**Comment by lwhite1** [comment]
Sorry @ccleva. I didn't realize there was a relatively new comment on this. If you were to do this, it would be a separate repo I think.

**Comment by ccleva** [comment]
No problem @lwhite1, as you can see I am sometimes slow in my communication...

I know this issue is closed but I wanted people still watching this thread to know that we just released the first public version of the tablesaw parquet reader !

It is available in the maven central repository. You can find all details in our github repository here: https://github.com/tlabs-data/tablesaw-parquet.

Feedback is welcome. I will open a discussion regarding how to best mention this external reader in the tablesaw documentation.

**Comment by yuj** [comment]
@ccleva Awesome. Also it's nice that you made it Maven ready.

**Comment by lwhite1** [comment]
@ccleva. This is great news. Thank you for the contribution.
