### ISSUE TITLE
ArrayIndexOutOfBounds when reading CSV file

### ISSUE THREAD

**Issue by kbvatral** [jtablesaw/tablesaw#297]
I have a CSV file that I am working on reading into TableSaw. I'm using the following code to read it:
```java
try {
    CsvReadOptions.Builder builder = new CsvReadOptions.Builder();
    builder.file(csvFile).header(false);
    data = Table.read().csv(builder.build());		
} catch (IOException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}
```

In this code, `csvFile` is a File object generated earlier in the code. At run-time, the following exception is thrown:

```
Exception in thread "main" tech.tablesaw.io.csv.AddCellToColumnException: Error while adding cell from row 34 and column C1(position:1): 1
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:229)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at DataUtils.importData(DataUtils.java:76)
	at App.main(App.java:14)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:227)
	... 3 more
```

The CSV was generated with another program and has one empty lines at the end. I tested this while manually removing the empty line and it seemed to work fine, so I'm guessing that's why the exception is being thrown.

I'm doing this import with files in batch, so it would no be preferable to remove the line for each file. It would be great if the CSV read functions in TableSaw checked for empty lines and skipped them or handled this exception another way somehow.

**Comment by lwhite1** [comment]
Hi Caleb,

To clarify, I expect the parser to handle the case where the last line has no CR, or has a CR (creating  in essence an extra line with zero bytes). It doesn't handle two (or more) carriage returns after the last bit of extra data.  Please lmk if that's not what you're seeing, because it should definitely handle one CR after the data. 

As far as the error goes, I will definitely fix the code so that it gives a better error message. This one is pretty useless for this use-case, and the use-case is probably not too uncommon.  I do think that having totally blank lines in a CSV is a 'bug' in the input data, though.  

That said, i sympathize with the problem of upstream data sources that produce bad data. I think I will just write the error condition to std.err and continue, but I will think some more on that. I will only do that if the line is completely empty though - no white-space other than the CR. 

If I decide to implement the "warn and keep going" change,  does tomorrow (in master) work for you?

**Comment by kbvatral** [comment]
Yes you are correct. It works exactly as expected with a single CR at the end of the file. The trouble I'm having is if there are empty lines other places in the file, or multiple CR at the end of the file.

I would agree with you that its more of a bug in the input data than a bug in the code. That being said, this isn't the first time I've encountered this in an upstream file, so I wouldn't be surprised if its fairly common. 

I can work around it, but it requires an extra pass over each data file, which is not ideal for scale. Its certainly not urgent, but anything you guys can do to help would be greatly appreciated!

**Comment by lwhite1** [comment]
I made the change. LMK if it works for you.

**Comment by kbvatral** [comment]
Yes that works perfect! Thanks so much for the help.
