### ISSUE TITLE
Read JSON data

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#374]
Supporting reads from JSON would make it easier to use Tablesaw with data from a RESTl API

From  @benmccann 

```
I had been thinking this might be a nice feature

The way I would implement this would be to use a library like Jackson to serialize the bean to
json and then use something like json-flattener to flatten the json. You could then iterate over
the json properties and read it into a Table

If you knew that the bean had no nested properties then you could convert the list to csv
 and then use Tablesaw's built-in csv reader. This solution wouldn't work in the general case, 
but might be easier for you to implement if you knew that you wouldn't have to deal with nested 
properties
```

**Comment by lwhite1** [comment]
I'm not sure I would get into the beans / objects to json business. That
seems like something client code could do easily, and perhaps better.

Reading from JSON seems useful, and the flattener seems like a good
approach to generalizing it. It would check a box on IO support that we
haven't yet checked. It would also make it easy to use tablesaw with the
results of a REST call.

OTOH, I don't think anyone has ever asked for JSON IO support. (Even this
request isn't for that specifically.)

Jackson is more powerful than GSON, I think, but I've always preferred GSON
when it was up to the task at hand.

**Comment by benmccann** [comment]
The main reason I suggest Jackson is because it's more powerful. We can support reading from JSON, CSV, beans, etc. all using Jackson.

The API is a bit more complicated, but this will be hidden form users.

Jackson is more performant than GSON from most benchmarks I've seen

Jackson is also more widely used, which means for most of my applications, I'm not including any new dependencies because Jackson is already included. E.g. I'm developing a web app which includes Tablesaw. Play Framework includes Jackson already, so I don't add to the size of the application by using Jackson. The other side of this is that I'm more likely to run into issues around conflicting versions of Jackson.

**Comment by lwhite1** [comment]
Those are pretty compelling reasons if we use it for CSV, JSON and Beans.
Etc., is XML, mainly?

**Comment by lwhite1** [comment]
You wrote:  We can support reading from JSON, CSV, beans, etc.

I was asking what etc encompasses.

**Comment by benmccann** [comment]
Oh, I see. I didn't have anything else specific in mind. I believe Jackson supports xml and yaml at least as well, but I'm not sure there's much reason to add support for those
