### ISSUE TITLE
Float vs Double

### ISSUE THREAD

**Issue by gregorco** [jtablesaw/tablesaw#385]
@lwhite1  The current support for Float column type appears to be behind the support for Double column type.  Is this intentional, or has there just not been resources available to work on it?   I’m experimenting on choosing the best java type when importing a database ResultSet into a Table and don’t see equivalent float/Float types for all the double/Double types I’ve found.  It’s not something I have a need for at the moment - was just curious as to its state.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lwhite1** [comment]
Sorry, I don't understand what this means: "don’t see equivalent
float/Float types for all the double/Double types I’ve found."

That said, new code on master is not something you should count on. That's
why it's still on master and not in a release yet.

**Comment by gregorco** [comment]
Sorry for the vagueness.  The main place that got me questioning it was in NumberFilters.java where the methods take double and DoubleColumn type inputs.  Just made me wonder if equivalent methods that took float and FloatColumn types would also be needed.  

Gregor

**Comment by benmccann** [comment]
We didn't want to make the implementation and maintenance too complicated by reimplementing every method for every type. We have the non-double numeric column types so that data can be held in memory in a less memory-intensive manner, but then actual computations will have to use double or else it'll be too hard to implement supporting every pair-wise type of numerics.

That being said I think we can loosen the constraints a little bit. I just changed `NumberFilters` to take `NumericColumn` instead of `DoubleColumn`. I didn't want to add lots of duplicate methods so left the other methods as taking `double` still

**Comment by lwhite1** [comment]
I think this is handled reasonably now, so i will close this.
