### ISSUE TITLE
How to set data type to whole Table.

### ISSUE THREAD

**Issue by Ebalaitung** [jtablesaw/tablesaw#415]
Hello tablesaw team.
I've question regarding setup of data type for the Table if I don't know the amount of colums.
I have 30_000x2000 feature csv file with 0.0 and some other amount of Double numbers.
If I call csv parsing via:
``` 
CsvReadOptions options = CsvReadOptions.builder(csv)
                    .header(false)
                    .maxNumberOfColumns(50_000).build();

Table t = Table.read().csv(options);
```
I got Number format exception, as all 0.0 number are treated as Short 0. So when reader gets to real numbers like 13.5 if throws NFE.

But if I add ``` sample(false) ``` to reader options if takes about 2:40 to parse such file.

How can I setup data type for whole Table, as far as I can see only by setting columnType in parser option, but it's won't work as I don't know a number of columns on csv file?

P.S. I used com.univocity.parsers.csv.CsvParser separately to read the same file so it takes 2:20 for parser.parsAll and 1:20 for parsing file by row.

**Comment by lwhite1** [comment]
If you can read the file once without sampling, you can get the column
types and pass them to the CsvReadOptions.builder.

It's documented here:
https://jtablesaw.github.io/tablesaw/userguide/importing_data.

cheers.

**Comment by lwhite1** [comment]
Well, I would run printColumnTypes once, copy the result, and paste it into
the code to use as a constant. What you're doing is the same as turning
sampling off.

> But looks a bit ugly.
>
> If you don't like the library, don't use it.

**Comment by Ebalaitung** [comment]
Yes, but sampling works incorrect for sparse matrices. My initial question was: is it possible to setup dataType for the whole Table in simple way.
So if you don't have any objections, I can contribute to this functionality.

**Comment by benmccann** [comment]
@Ebalaitung I also ran into an issue with sampling being too aggressive on sparse matrices. I just released 0.30.1 which may help with that issue. Can you try the new version with sampling and see if that fixes your issue? (you may need to wait for up to an hour from the time I leave this comment for the new version to show up)

What is the API you're proposing for setting up the data type?

**Comment by Ebalaitung** [comment]
> What is the API you're proposing for setting up the data type?
What about .setColumnsType for *ReaderOptions object.

**Comment by Ebalaitung** [comment]
@benmccann I've tested 0.30.1 version with sampling and it works fine. But still performance is the issue.

**Comment by benmccann** [comment]
@Ebalaitung you're in luck. That API exists already: https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java#L269

**Comment by Ebalaitung** [comment]
@benmccann, nope. As you can see above, this API works if we know amount of columns in the csv. I propose to add method, which defines type for all columns, instead of creating an array with similar types.

**Comment by benmccann** [comment]
It's still not exactly clear to me what you want to be able to do. You want to say that every single column is of the same type and what that type is?

**Comment by Ebalaitung** [comment]
Yes, exactly!

**Comment by lwhite1** [comment]
I think that feature is too specialized to be added to the API

**Comment by benmccann** [comment]
I agree that feature seems rather specialized and I think we probably shouldn't support that API. A couple other ideas that might help here though:

* I maybe could see a case where users have smaller tables and don't care about the memory savings from int, short, etc. columns. In that case maybe it would be easier for them to specify that all number columns be double columns?
* Perhaps the number of rows to sample should be configurable. We just increased the number of rows to sample from, but it seems like maybe we made it too large for this case where the CSV also has a huge number of columns. Perhaps we should make it configurable so that the user can choose a smaller  or larger value in cases where that would help? This seems like the API more likely to be widely used, so I'd probably suggest just making this change and waiting to see if other people request the column type option before considering whether to make that change

@Ebalaitung you could use `Arrays.fill` to fill your array, which would cut out a few lines of code. Also, I recommend not calling `detectColumnTypes` since that will take a fair amount of time and instead use Univocity to just parse the first couple lines of the file to figure out how many rows there are.

**Comment by Ebalaitung** [comment]
Ok, I've got your point. Will use workarounds provided above.

**Comment by R1j1t** [comment]
I think there is a bug in excel import. As mentioned by @Ebalaitung to use `sample(false)` for csv, that particular option does not work for Excel import even though you can set it in `ExcelReadOptions`. For example, if we use the below table in excel, it will take both the column types as `NUMERIC` because the **first cell** in both columns is an integer/float as mentioned in here:

https://github.com/jtablesaw/tablesaw/blob/master/excel/src/main/java/tech/tablesaw/io/xlsx/XlsxReader.java#L261-L267 

```java
      for (int colNum = 0; colNum < headerNames.size(); colNum++) {
        Cell cell =
            row.getCell(colNum + tableArea.startColumn, MissingCellPolicy.RETURN_BLANK_AS_NULL);
        Column<?> column = columns.get(colNum);
        if (cell != null) {
          if (column == null) {
            column = createColumn(headerNames.get(colNum), cell);
            columns.set(colNum, column);

```


| col 1    | col 2    |
|----------|----------|
| 1.00     | 11.00    |
| 2.00     | String 2 |
| 3.00     | 13.00    |
| String 1 | 14.00    |
| 5.00     | 15.00    |
| 6.00     | 16.00    |

**Comment by wcneill** [comment]
I know this is closed, but I'm going to plug for this functionality anyway. It doesn't seem "too specialized" at all. 

The suggestion to "read a table then copy and paste its types" is far from programmatic and becomes impossible to automate. If we were all just working in Jupyter notebooks, I'd not be complaining but I'm trying to develop software.

**Comment by lwhite1** [comment]
if you're reading a CSV file, there is an option in CsvReadOptions that
lets you specify the types to be used when you read the file. If you just
provide one type (e.g. STRING), they would all be the same.  IDK if this is
implemented for Excel, however.
