### ISSUE TITLE
Add support for fixed-width files

### ISSUE THREAD

**Issue by Sparow199** [jtablesaw/tablesaw#428]

**Comment by Sparow199** [comment]
Hello, i'm working on this issue in my fork, if this feature is interesting and could be merged in the main project, i'll work on it but i need some help :). 
It's based on [univocity_parsers_fixed_width](https://www.univocity.com/pages/univocity_parsers_fixed_width.html#working-with-fixed-width) like the current csv parser of Tablesaw.

**Comment by benmccann** [comment]
I suppose I would be okay adding this feature if it does not add new dependencies

**Comment by lwhite1** [comment]
I think the simplest solution (though not necessarily the best) would be to pre-process the file to convert it to a delimited file. Inheriting from the CSV classes seems like a bad design from an OO perspective, simply because a Fixed Width file is not a specialization of a CSV file. 

I would have to reacquaint myself with the CSV implementation to be sure, but I think duplicating the classes would make the most sense. It may be desirable in doing so to extract a common interface first and have both CSV and FWF classes implement it.

**Comment by Sparow199** [comment]
Hello and Happy new yea 2019,

Actually, i'm working with duplicated classes solution, but i'll make it cleaner before making the PR.
The list of features for fixed-width-files is:
- Parsing Fixed width format with same pattern for all the lines (Done).
- Parsing (multiple line types) with lookahead (Done).
- Parsing (multiple line types) with lookahead, and a default format (Done).
- Parsing (multiple line types) with lookbehind (Done).
- Testing (Partially, need more testing).
- Add column types detection for multiple line types (Working in progress).
- Add skip invalid row option (Done).
- Cleaning code (Not yet).
- Optimise code (Not yet).
- Add more efficient logging strategy.
- Make a PR(Soon).

Thanks!

**Comment by lwhite1** [comment]
Very cool.  Thanks for your help

**Comment by Sparow199** [comment]
Hello, i'm very busy, i'll make the PR as soon as possible but only with the support  of parsing Fixed width format with same pattern for all the lines. It's the most stable. For multiple types, i need to find a way to link between parsed lines(ex Client and their accounts, i'll get two Tables without a relation between client and account). If there is no relations between lines, the actual implementation is working.
Thanks.

**Comment by lwhite1** [comment]
implemented. Thanks @Sparow199
