### ISSUE TITLE
Table.toString() throws exception when not all columns have the same length

### ISSUE THREAD

**Issue by deveborn** [jtablesaw/tablesaw#438]
I recognized that printing out a Table may result in an exception.  I guess it should not. Here is a working example:

```
public class IssueReview {

	public static void main(String[] args) {
		
		//Read sample file
        File file = new File("D:/levelsample.csv");
        Table table=null;
        try {
            table = Table.read().csv(file);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //print out the table
        System.out.println(table);
        System.out.println(table.structure());
        
        //add a column to the Table
        table.addColumns(StringColumn.create("foo"));
        
        
        //following throws an IndexOutOfBoundsException
        //try to print modified table...
        System.out.print(table);

	}

}

```
[levelsample.txt](https://github.com/jtablesaw/tablesaw/files/2763647/levelsample.txt)

**Comment by lwhite1** [comment]
Tables are supposed to be rectangular - that is, they're expected to have the same number of rows in each column. I think we used to throw an exception when adding an empty column to an un-empty table but some people wanted to fill the table after the fact. I guess there are a few things we might try:
1. Leave it alone (call it operator error)
2. Throw an error if the columns aren't all the same size.
3. Fill the column with missing values if you add an empty column. The problem here is that you have to then use set(index, value) to fill the column, whereas before you add it to the table you would use append(). This might seem arbitrary and be hard for people to understand. 
Any other options?

**Comment by benmccann** [comment]
I probably like 1 or 4 best since they still allow you to fill columns after the fact. 4 is probably the user-friendlier option of the two

**Comment by deveborn** [comment]
As a newbie I would prefer if the table was printed in some way even if its corrupt (in particular when it has been ok to create it) . But in that case it would be great if the output also clearly speak out that the Table is invalid (some kind of warning). I am not sure what you mean with nr 1 but if an exception should be thrown it would be nice if it describes the reason better than it does now (IndexOutOfBoundsExceptions is a bit anonymous to me). I think both these alternatives are good.

**Comment by lwhite1** [comment]
Fixed by ensuring Tables throw exceptions when a column added has a different size from the other columns in the table.
