### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by deveborn** [jtablesaw/tablesaw#439]
Following at [https://jtablesaw.github.io/tablesaw/gettingstarted](https://jtablesaw.github.io/tablesaw/gettingstarted) does not compile (because of scnd and third line):

```java
        double[] numbers = {1, 2, 3, 4};
        NumberColumn nc = NumberColumn.create("Test", numbers);
        out(nc.print());

```

Probably should be something like this?

```java
        double[] numbers = {1, 2, 3, 4};
        NumberColumn nc = DoubleColumn.create("Test", numbers);
        System.out.print(nc.print());
```

**Comment by benmccann** [comment]
Yes, thanks. I updated this quite a few places. I'd probably use `DoubleColumn` on the left side as well so that you don't get a generics warning

We should probably use something like https://developer.lightbend.com/docs/paradox/current/ or another alternative to make sure the code in the docs compiles
