### ISSUE TITLE
Add new maxCharsPerColumn parameter in CsvReadOptions

### ISSUE THREAD

**Issue by Njuton** [jtablesaw/tablesaw#471]
The default value of parameter maxCharsPerColumn in CsvParserSettings class is 4096, but i work with big text data and now i get an error:

Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096). 
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have

**Comment by lwhite1** [comment]
This seems reasonable. We have some folks working on a large pull request in this area, but I will add this feature when they're finished. 

Be sure to use TextColumn rather than StringColumn for work like this as StringColumn would be very inefficient memory-wise for this kind of data. It's designed for repetitive categorical strings.

**Comment by lwhite1** [comment]
implemented.
