### ISSUE TITLE
Fix NoClassDefFoundError caused by optional modules

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#485]
I messed up here because `DataFrameReader` imports the read option sub-types

```
tornadoes = Table.read().csv("../resources/data/tornadoes_2014.csv")
> java.lang.NoClassDefFoundError: tech/tablesaw/io/xlsx/XlsxReadOptions
```

Some easy options for fixing:
- Change API to `Table.read().xlsx().file(XlsxReadOptions)`
- Change API to `Table.xlsx().read(XlsxReadOptions)`
- Change API to `Table.read().xlsx(ReadOptions)`

Or the other option would be to finally implement the registry. I think I'll take a stab at that. CC @hallvard

**Comment by benmccann** [comment]
@lwhite1 @hallvard what do you think about changing the reader API to the following:
```
Table.read().url(String|URL url)               // choose reader via mime type
Table.read().url(ReaderOptions options)        // choose reader via ReaderOptions subclass type
Table.read().file(String|File file)            // choose reader via file extension
Table.read().file(ReaderOptions options)       // choose reader via ReaderOptions subclass type
Table.read().contents(String contents, String extension)
Table.read().contents(ReaderOptions options)   // choose reader via ReaderOptions subclass type
```

This will remove all type-specific info from the API, which will solve the `NoClassDefFoundError` error we're getting in master. It will also allow users to register their own custom reader types.

**Comment by benmccann** [comment]
We might also need a `readMultiple()` to live alongside `read()` because the `XlsxReader` returns `List<Table>` whereas the rest of the readers return `Table`

**Comment by hallvard** [comment]
I like having general methods where the actual reader is selected implicitly, based on file extension and/or mime type. How would you provide ReadOptions for the url, file and string methods? Couldn't you just add a ReadOptions argument, that may also select a specific reader in the string case and override file extension and/or mime-type for the other.
I'd leave out the readMultiple for now, since it particular for only one file format. If you need it you may use that reader directly. In cases where you only want one table from an xlsx file, you can provide XlsxReadOptions that select a specific sheet or region (not a current feature, but it may be handy when the default detection algorithm doesn't work)

**Comment by hallvard** [comment]
I'm doing some reflection on the Table class and this gives a NoClassDefFoundError when the smile module isn't present, due to the smile method in the Relation superclass having SmileConverter as its return type. I suggest giving up the fluid API design in cases where you cross modules, i.e. instead of a fluid method Xyz Table.xyz(...) you'll need something like new Xyz(Table, ...).

**Comment by benmccann** [comment]
Yeah, I have a follow-up PR that should fix this. Will send it in the next day or so

**Comment by lwhite1** [comment]
Without giving up the fluid api?

**Comment by benmccann** [comment]
Smile is quite unlike the readers. With the readers, we don't want the users to have to know which JSON library we're using, etc. So having the users import `tablesaw-json` hides this from them. With the Smile integration however, the user is explicitly choosing to use Smile and probably wants to control which version of Smile they are using, etc. So I ended up reverting the change to move Smile out to a separate module. I think that change only made sense for the readers.

Hopefully all the `NoClassDefFoundError` should be fixed now
