### ISSUE TITLE
poms in html, excel, and json projects reference older version of core

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#502]
Is this by design? 

```
    <dependency>
      <groupId>tech.tablesaw</groupId>
      <artifactId>tablesaw-core</artifactId>
      <version>0.32.2</version>
      <scope>provided</scope>
    </dependency>


```

**Comment by benmccann** [comment]
Yeah, I wish you could make the version match, but sadly that results in a circular dependency, which Maven won't compile. Since it's `provided` it doesn't actually get pulled in and it doesn't really have any effect that the version is older

The only one downside to using a different version is that you can't introduce a change in core and use it in the reader libraries in the same PR. You have to split up the changes. I think the only way around that would be to remove the `Table.read()` methods and make folks do `new JsonReader().read`, etc.

**Comment by lwhite1** [comment]
i figured it was something like that. Closing.
