### ISSUE TITLE
reflections output in log file

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#503]
My application log for a project that uses tablesaw has this in the file: 

```
2019-03-28 11:52:31 INFO : Reflections took 56 ms to scan 2 urls, producing 10 keys and 27 values 

```
It was a little disconcerting to read about something scanning urls in my app. If I didn't know Reflections was a library tablesaw uses, it would be more disconcerting I imagine. Can we stop it from doing what it's doing or suppress the message?

**Comment by benmccann** [comment]
I believe this message will not show up for users who do not have logging configured. E.g. if I run `Example1.java` then I don't see it

For users who do have logging configured, the user can disable log messages coming from a certain class or package such as `org.reflections` in the configuration file for their logging framework.

I haven't tested this, but looking at their code it seems like we can actually set `Reflections.log = null` to disable their logging. While it technically works, I'm not sure I really like that solution because if the user was using reflections for anything else and wanted log output it could be confusing to that they can no longer configure the reflections logging in their logging configuration file.

Probably the cleanest solution would be to file a request in the reflections tracker requesting that they change the log level of that message from `info` to `debug`. By default, most logging libraries show info logs and above and this is perhaps not a log that really needs to be included in every consumer's logs

**Comment by lwhite1** [comment]
I like that solution.  I wouldn’t care except people could get nervous
seeing something scanning ports
