### ISSUE TITLE
Type detection improvements

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#515]
`FileReader`'s `List<ColumnType> typeDetectionList` should probably be part of the `ReadOptions` so that there's an easy way to pass it in when using the `Table.read()` methods and it can be used by the other classes like `HtmlReader` and `JsonReader` as well

I'm wondering if `minimizeColumnSizes` should apply to `DateColumn`/`DateTimeColumn` as well. I'm dealing with a bunch of different data sources and would prefer to just have `DateTimeColumn`s in my application so that I don't have to worry about which type of date column I have. This is similar to not wanting to worry about what number type a column is and just using `DoubleColumn` everywhere

What do you think @lwhite1 ?

**Comment by lwhite1** [comment]
> FileReader's List<ColumnType> typeDetectionList should probably be part of the ReadOptions
Makes sense.

> I'm wondering if minimizeColumnSizes should apply to DateColumn/DateTimeColumn
I'm not so sure about this one. I can see your point but since there's a semantic difference here, rather, where for the other column types the differences are about efficiency and the details of representation things in a computer. 

I'm a bit more concerned because doing it with minimizeColumnSizes means it would be the default for everyone. What about adding a flag for this?
