### ISSUE TITLE
Column.countUnique() returns a wrong value after using Column.set()

### ISSUE THREAD

**Issue by ccleva** [jtablesaw/tablesaw#541]
Hi,

After assigning all values to a previously empty Column, the empty value is still counted by countUnique().  Below is a simple test case demonstrating the issue. The count is correct when the column is created with no size and append() is used (2nd test case).

```
import static org.junit.Assert.*;
import org.junit.Test;
import tech.tablesaw.api.StringColumn;

public class TestTablesawUniqueValues {

	@Test
	public void testUniqueValuesAfterSet() {
		StringColumn col = StringColumn.create("col1", 2);
		col.set(0, "A");
		col.set(1, "B");
		assertEquals("Error in unique() after set()", 2, col.countUnique());
	}

	@Test
	public void testUniqueValuesAfterAppend() {
		StringColumn col = StringColumn.create("col1");
		col.append("A");
		col.append("B");
		assertEquals("Error in unique() after append()", 2, col.countUnique());
	}
}
```
Test result:
java.lang.AssertionError: Error in unique() after set() expected:<2> but was:<3>

Tested on version 0.34.1

Thanks for tablesaw !

**Comment by benmccann** [comment]
Thanks for the unit tests!!

It looks like `unique` is broken as well. This bug appears to only affect the `StringColumn`

**Comment by benmccann** [comment]
So when you create a `StringColumn` with the size initialized, it creates a `ByteDictionaryMap` to store the column data internally and appends missing values to fill the empty space. When you call `map.set` the `StringColumn` uses `rowIndex` as the key. But when you call `map.appendMissing` it uses `MISSING_VALUE` as the key. I'm wondering if the bug is that it shouldn't be using `MISSING_VALUE`, but rather should be using `rowIndex`. @lwhite1 can you share what the intended usage of `ByteDictionaryMap` in `StringColumn` is and how it should deal with missing values?

**Comment by lwhite1** [comment]
The ByteDictionary is part of the implementation for dictionary encoding for strings. If there are few unique values it uses a byte, otherwise a short or int depending on the number of values, so there are similar data structures for those.

There should be one entry for each unique value in the column, including missing values

**Comment by benmccann** [comment]
What are the key and value for the dictionary supposed to be?

**Comment by lwhite1** [comment]
There are two maps and an array (really a ByteArrrayList) inside
ByteDictionaryMap. One map holds Strings to bytes and the other bytes to
Strings. The Strings are the values. The bytes are keys. The array itself
contains they keys. This is the StringColumn's "data".

The String to Byte map is used for lookups: Given a String you find the
associated byte. Then the array is scanned for the matching bytes and a
Selection is returned, IIRC.

The Byte to String map is used to enumerate the values in the column. To
return the first 10 strings, read the values from the first ten array
positions and look up in the associated strings in that dictionary.

Without having looked at this specific problem in detail, I suspect the
easiest fix is to initialize the column with an arrayList of size 0 unless
the user provides a size. The only complication is that StringColumn is
really a wrapper for the underlying DictionaryMap, and as I mentioned there
are three implementations of that interface. (StringColumn starts with a
ByteDictionary and transitions silently as needed, first to a
ShortDictionaryMap and then an IntDictionaryMap when the number of unique
values in the column requires.

**Comment by benmccann** [comment]
Thanks Larry! That's super helpful

The problem is that if a value is removed, it's not cleared from the maps. The map is used to compute `unique`. As a result, both of the tests below fail:

```
    @Test
    public void countUniqueSetEmpty() {
        StringColumn col = StringColumn.create("col1", 2);
        col.set(0, "A");
        col.set(1, "B");
        assertEquals(2, col.countUnique());
    }

    @Test
    public void countUniqueSetAfterAppend() {
        StringColumn col = StringColumn.create("col1");
        col.append("A");
        col.append("B");
        assertEquals(2, col.countUnique());
        col.set(0, "C");
        col.set(1, "D");
        assertEquals(2, col.countUnique());
    }
```

This is also potentially a memory leak if a user were to repeatedly set different values. Though I'm not sure how likely that is.

I suppose in `set` we can get the old value at that location in the column and then check if the `values` list still contains it after the set. However, that changes `set` from `O(1)` to `O(n)`. So to keep if fast we probably want the `valueToKey` map to store not only the key, but also the count of number of times the value is present in the column

I don't use the `StringColumn` at all, so I'm unlikely to fix this issue myself, but I hope that provides enough detail on the issue that anyone who's motivated to fix it can do so.

**Comment by ccleva** [comment]
Thanks for the detailed explanation. I will try to implement a fix if I have some time later, but this may take some time as I don't know the project very well yet.

**Comment by lwhite1** [comment]
@ccleva Thanks for looking at this. I may take a look also when I get back from vacation mid-july if it's still open.

**Comment by lwhite1** [comment]
Having slept on it, i think the best solution is to do instance counting: I can't think of another way to determine whether a String is the last of its type in the column without doing full scans on every set or delete. 

This of course introduces more complexity.  Two options

(A) Introduce another map - from the byte value to a count and increment it on inserts, decrement on deletes and do both on updates. 

(B) The alternative would be to modify the existing byte-to-string map to hold an object containing the string and it's count. This is probably best because otherwise the amount of coordination between maps and the array would increase. 

Either way, entries in all maps should be removed when the count gets to zero.

These changes might affect the code for copying columns (and tables, by extension), so that needs to be checked.

**Comment by ccleva** [comment]
I went with solution A to avoid having to create new objects containing the String and its count. Coordination required is not much of an issue, as you can see in the PR.

Let me know if the code needs some modifications / documentation.
