### ISSUE TITLE
JSON Reader Column Detection favoring Integer Column Type Over String

### ISSUE THREAD

**Issue by ryancerf** [jtablesaw/tablesaw#592]
Currently JSON like the sample below is being auto detected as an Integer Column. Is this desired? I find it a bit surprising.

```java
// Note the quoted number.
String json = "[" +
      "{\"A\" : \"123\"}]";
```

**Comment by benmccann** [comment]
It uses `ColumnTypeDetector` which is also shared by CsvReader, etc.: https://github.com/jtablesaw/tablesaw/blob/160fee0b09cedc3b00d6e9eca8ea81e441a0e528/core/src/main/java/tech/tablesaw/io/TableBuildingUtils.java#L18

It will try to use columns in the order specified here:
https://github.com/jtablesaw/tablesaw/blob/160fee0b09cedc3b00d6e9eca8ea81e441a0e528/core/src/main/java/tech/tablesaw/io/ReadOptions.java#L43

It'll use a double column if you have an entry with a decimal part

**Comment by lwhite1** [comment]
@ryancerf 

It will use an IntColumn if you hand it ints. Otherwise you end up with things like ids and indexes having decimal places and you use much more memory than is necessary.  

You can
- force it to use doubles by providing the types when you read the file, or 
- convert it after the fact, or 
- (maybe) modify the type list that @benmccann pointed out. 

If that list _is_ exposed, you can force it to load nothing by doubles for any numeric value by removing the other options.

**Comment by ryancerf** [comment]
@lwhite1  I am sorry, I should have been way more specific. I was expecting the above example to return a String. I think the Integer vs Double logic makes sense. 

More detail:

I expected this to be parsed as a string (Note quotes around 123). It is currently being parsed as an Integer.
```java
String json = "[" +
      "{\"A\" : \"123\"}]";
```

This is correctly parsed as an Integer (Note the lack of quotes around 123)
```java
String json = "[" +
      "{\"A\" : 123}]";

**Comment by lwhite1** [comment]
¯\\_(ツ)_/¯

I guess you could have zero padded numbers representing an ID or something, but it seems like a minor concern to me. If the string is not zero padded it will sort incorrectly. (i can't imagine many people wanting to sort an integer list lexically:  1, 11, 2...) 

We try to map things in a way that minimizes total difficulty over the whole user community so we have erred on the side of leniency since many data sets are poorly constructed. We also try to make semi-intelligent guesses about what was intended. In json, "2020-11-4" is just a string, but we treat it as a date anyway. 

We can't treat "123" as a string in CSV, because the standard allows quoted numbers, so we'd have to interpret json differently, which is fine. It might help when reading data from a rest API or something.
 
I'm not sure it's worth the effort, but feel free to submit a PR. It should probably eliminate the other fuzzy bits we do as well, like treating columns containing only "true" and "false" or "T" and "F" as boolean, since that's also incorrect according to the spec.

**Comment by ryancerf** [comment]
Thanks for the explanation. The goal is not to read JSON to spec. The goal is to pick data types that will be useful for data analysis. If this issue comes up a few more times maybe we can address it, but I think you are right. It is not worth the effort.
