### ISSUE TITLE
NumberColumn and StringColumn count unique values differently

### ISSUE THREAD

**Issue by ryancerf** [jtablesaw/tablesaw#594]
NumberColumn and StringColumn count unique values differently

* StringColumn includes missingValues in countUnique.
*NumberColumn does not include missingValues in countUnique.

See PR #593 for tests detailing the issue.

We should pick one method and and be consistent. @lwhite1 What is your preference?

**Comment by benmccann** [comment]
It looks to me like Pandas includes missing values, so that might be more expected for users who are familiar with how that library works

Also, if we include missing values, then it's easy enough to drop missing rows before or after doing the `unique` that users could then get either behavior depending on what they want. If we filter it out automatically then it's less flexible for users who have a use case where they want missing values

**Comment by lwhite1** [comment]
> It looks to me like Pandas includes missing values, so that might be more expected for users who are familiar with how that library works

Works for me
