### ISSUE TITLE
Use a faster data structure for isIn membership check on TextColumn

### ISSUE THREAD

**Issue by ryancerf** [jtablesaw/tablesaw#611]
`isIn` is implemented using an array list for TextColumn. Use a set or something else with O(1) lookup.

**Comment by ryancerf** [comment]
This makes me wonder whether TextColumn should support `isIn`.

**Comment by lwhite1** [comment]
you're talking about exact matching the value of a entry against a list of candidates, right?

I think this is needed, and would really like the difference between StringColumn and TextColumn to be limited to the implementation rather than appearing in the interface. Also, isEqualTo() has the same problem and I wouldn't want to drop that.

A hash set will probably not help because if their were a lot of repeat values it would already be a StringColumn. A tree set could help, or perhaps some kind of tree designed for term searching), if it doesn't take too long to build. The latter might also help with the performance of containsString("foo"), also.

**Comment by ryancerf** [comment]
> I think this is needed, and would really like the difference between StringColumn and TextColumn to be limited to the implementation rather than appearing in the interface. Also, isEqualTo() has the same problem and I wouldn't want to drop that.

Makes sense. Thanks for the explanation.

Regarding performance, I was simply thinking the collection of strings passed in to the isIn method would be better off in a HashSet. 

Consider the SQL example below (which is a common use).

```sql
SELECT *
FROM myTable
WHERE region IN (SELECT * FROM region);
```
In tablesaw:

```java
myTable.where(text("region").isIn(region.stringColumn("region").asList()));
```

The current implementation would take O(nk) time where n is the number of rows in myTable and k is the number of rows in the region table. If you put the list of regions into a HashSet it is O(n), because a lookup in a HashSet takes amortized constant time regardless of the number of elements it contains. See the PR for more details.
