### ISSUE TITLE
CSV file type inference sometimes returns LocalDateTime instead of String (again/still)

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#623]

**Comment by lwhite1** [comment]
this happens when the columnType selector doesn't hit any non-missing values,  which can happen if the column is empty or if the rows with values are missed if sampling is used.

I think the fix is to do a missing value check on each row before trying to parse it, and setting a boolean if we hit a non-missing value.

**Comment by benmccann** [comment]
It seems like this issue is possibly more general. When you sample you might not see a value that causes a column type to be correctly chosen. I wonder if we could create a more general fix. E.g. if you encounter a parsing error then see if there's a column type that would not cause the parsing error and where you can convert the previously chosen column type to the new type

**Comment by lwhite1** [comment]
I don’t think that’s a more general fix on its own.  If the column is empty
there won’t be a parsing error.

The fix I described returns us to what the status quo should be. We could
implement re-parsing on top and have a better solution.

**Comment by benmccann** [comment]
If there is legitimately no data in the column and it's not just a sampling error then how can you say what the right column type is?  Though I suppose `LocalDateTime` is a weird default for an empty column. Was that your point? I think I'd agree in that case

**Comment by lwhite1** [comment]
yeah that's it. You get columns with names like "City", or "Percent
passing" with a type of LOCAL_DATE_TIME, and that looks bad.

I will open a new issue with your enhancement, which I think will be
wonderful.

**Comment by lwhite1** [comment]
fixed
