### ISSUE TITLE
After joining two Tables, in the resulting Table the second join column is missing.

### ISSUE THREAD

**Issue by Aghalaryan** [jtablesaw/tablesaw#692]
Regardless of the join type or the types of the columns acting in join, I could not make operations with the second column as it was missing from the result. Is it a normal use case? If yes, how can I prevent this instead of adding second column with appropriate data manually?

**Comment by benmccann** [comment]
Shouldn't the second column and first column contain the same values? Why would you need two copies of it?

**Comment by Aghalaryan** [comment]
Yes, for Inner join. For outer joins we loose "null" values. I need to work directly with second column. Tables join reordering will not work for left/right outer joins.

**Comment by ryancerf** [comment]
As a workaround you could create a copy of the join column before joining. Since the copied column has a different name it will not get dropped.

**Comment by Aghalaryan** [comment]
Actually, I do not want to duplicate and modify column because it is not clear how big could be the data. For now workaround can be satisfying, but are there any plans for returning all the columns?

**Comment by Aghalaryan** [comment]
Also, reading from jdbc resultset fails for json datatype. Could you, please, add it to your mapping? 
Thank you.

**Comment by benmccann** [comment]
Yeah, returning the second column would make sense for outer joins. I wrote the inner join first, so didn't consider that case. I would be open to a PR. We'd have to figure out the right API (e.g. renaming the second column to avoid collision, should there be an option to control this feature, etc.)

Re: json datatype. I probably won't add it because I don't have a database setup with a json datatype, but again would be open to a PR adding support

**Comment by Aghalaryan** [comment]
Thank you, looking forward to upcoming versions.

**Comment by DanielMao1** [comment]
@benmccann Hello, I think this issue can be implemented by adding a set of overloading methods of joining. I issued a PR  for this. If you are still interested in this issue, can you find time to have a look?

**Comment by lwhite1** [comment]
fixed
