### ISSUE TITLE
DoubleColumn: using scala list to create

### ISSUE THREAD

**Issue by 2533245542** [jtablesaw/tablesaw#780]
Hi,
I was using tablesaw in scala and I found a very difficult time converting scala data to tablesaw structures. For example, below code does not work because list is not a double array. 
```scala
        var list = List[Double]()
        DoubleColumn.create("a", list.asJavaCollection)
        DoubleColumn.create("a", list.asJava)
```
I found a way to step over it, by creating a column first and then using append. But it would be nice to have a better solution. 
```scala
val col = DoubleColumn.create("a")
col.append(1)
col.append(2)
```
BTW, it would be nice to sampleN or sampleX with replacement, too

**Comment by benmccann** [comment]
I would expect that to work because we have a method `DoubleColumn.create(String name, Collection<Number> numberList)`

**Comment by benmccann** [comment]
Ah, though I just realized that should be `DoubleColumn.create(String name, Collection<? extends Number> numberList)`

I fixed that here: https://github.com/jtablesaw/tablesaw/commit/2b9768db339dd342dc6e0ef54cf00504b0876b42

The fix should be part of the next release, but in the meantime I think you can just use `toArray` instead of `asJavaCollection`
