### ISSUE TITLE
leftOuter join will only join to the last table included in the list

### ISSUE THREAD

**Issue by lucasvwamp** [jtablesaw/tablesaw#807]
If multiple tables are passed to a leftOuter join, only the last table in the list is actually joined in the return value. This is because of the line linked below. joined is reset for each iteration

https://github.com/jtablesaw/tablesaw/blob/ae52d999e0ee1152012ff6e18ac9bd031eacfea4/core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java#L453

**Comment by Carl-Rabbit** [comment]
@lwhite1 @benmccann Hi, developers. I also noticed this problem when I use leftOuter join. I think there are two acceptable solutions:

1. Let the function `leftOuter` accept only one table
2. Fix it by modifying `DataFrameJoiner.java`

If you think this issue is worth fixing, I'll be happy to help! 
Thanks a lot and look forward to your reply

**Comment by benmccann** [comment]
Yes, we should fix it rather than modifying the method signature

**Comment by lwhite1** [comment]
I'm not entirely convinced that support for multi-table joins was ever a good idea. It's relatively easy for a developer to chain together individual join statements to accomplish the same thing. It also significantly complicates the join code, making it harder to do things like performance improvements. 

Personally, i never use it, in part because I don't trust the existing code, but also in part because it's so easy to work-around for most use cases. 

Is there any situation where you cannot simply call something like:

```
   a.leftOuter(b).leftOuter(c).leftOuter(d)....

   // or

  x = x.leftOuter(b);
  x = x.leftOuter(c)...

```
(I know that's not real code, but it suggests the solution.)

**Comment by benmccann** [comment]
I'll go ahead and merge the fix since it doesn't stop us from reconsidering the API if necessary
