### ISSUE TITLE
No column detected from CSV with no data (header row only) 

### ISSUE THREAD

**Issue by AlexandreGarino** [jtablesaw/tablesaw#815]
Hi,

I read a CSV file with no data (header row only) and I noticed that no column was detected. 

The resulting table is empty.

```java
final ByteArrayInputStream inputStream = new ByteArrayInputStream("Column1;Column2;Column3\n".getBytes(StandardCharsets.UTF_8));

final CsvReadOptions readOptions = ((CsvReadOptions.Builder) CsvReadOptions.builder(inputStream)
        .columnTypesToDetect(Arrays.asList(ColumnType.STRING)))
        .header(true)
        .separator(';')
        .build();

final Table table = Table.read().csv(readOptions);

assertThat(table.columns(), hasSize(0)); // OK
```

Did I make something wrong?

Any help would be greatly appreciated.

**Comment by lwhite1** [comment]
I guess this would be a bug, but a fairly minor one from my perspective. 

I don't see the use-case for reading a file with nothing but a header line. Tablesaw is geared more towards analyzing existing datasets than on building datasets in memory. Of course you *can* create a table entirely in code, but I've only ever used that for testing.

Have you found any work arounds? I think i would look at either (a) trying to load the file with the column types pre-specified (I notice all your columns are strings), or (b), just reading the headers using a standard java file reading approach and creating the table in code, by looping over the names

**Comment by AlexandreGarino** [comment]
Hi,

The code snippet is here just to reproduce the bug.

The real code scan pragmatically a folder for new CSV files and apply some business logic (we compute new column based on existing columns) on some criteria.

For now, when we read the table, if the table is empty we copy the file as-is.

**Comment by imagejan** [comment]
Is there an option now for keeping all columns when reading a header-only file (even when the column *types* can't be determined of course)?

In our use case, we write many tables automated in batch, and some of them could potentially end up being empty. Nevertheless, we have the same column headers across files. Currently, we get an exception (in MoBIE which depends on tablesaw) because tablesaw returns a `Table` without columns at all. I would have expected at least all the `columnNames()` be the same as in the (header-only) input file.
