### ISSUE TITLE
CsvReader depends on system default charset

### ISSUE THREAD

**Issue by DrIgor** [jtablesaw/tablesaw#837]
Run this snippet:
```java
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.charset.Charset;

import tech.tablesaw.api.Table;
import tech.tablesaw.io.csv.CsvReadOptions;

class Scratch {

    public static void main(String[] args) throws IOException {
        System.out.println(Charset.defaultCharset());
        Reader reader = new StringReader("колонка_А,колонка_Б,колонка_В"); // cyrillic
        CsvReadOptions options = CsvReadOptions.builder(reader).header(false).build();
        Table dataset = Table.read().usingOptions(options);
        System.out.println(dataset);
    }
}
```
Its output depends on java `file.enconding` system property.

`-Dfile.encoding=UTF-8` works as expected:
```
UTF-8
                                         
    C0      |     C1      |     C2      |
-----------------------------------------
 колонка_А  |  колонка_Б  |  колонка_В  |
```
But `-Dfile.encoding=US-ASCII` breaks non ascii characters:
```
US-ASCII
                                         
    C0      |     C1      |     C2      |
-----------------------------------------
 ???????_?  |  ???????_?  |  ???????_?  |
```
Using `Source` with input stream and explicit encoding doesn't help

The reason is CsvParser uses `String.getBytes()` with default encoding. See https://github.com/jtablesaw/tablesaw/blob/51883b51f36f4d57c76abaa238d09c6def275a73/core/src/main/java/tech/tablesaw/io/csv/CsvReader.java#L65

**Comment by lwhite1** [comment]
I'm not sure if this is a reader issue or a writer issue. Or both

**Comment by DrIgor** [comment]
The line
https://github.com/jtablesaw/tablesaw/blob/51883b51f36f4d57c76abaa238d09c6def275a73/core/src/main/java/tech/tablesaw/io/csv/CsvReader.java#L65
calls `getBytes()` without encoding so it can corrupt some characters. I suggest declaring `bytesCache` as a String, not byte array or hardcoding some safe encoding like utf-8

I don't know if writes has similar problem

**Comment by lwhite1** [comment]
ok. I will try to find time to look into it. Thanks for the report.

**Comment by lwhite1** [comment]
I'm not sure I would hardcode an encoding. There are probably scenarios where that would cause problems, and the user would be helpless.  Since the current behavior is to use the default, it may break someone's code.

My preference  would be to add encoding as a ReadOption (or CsvReadOption), with the system default serving as the Tablesaw default.

**Comment by lwhite1** [comment]
Reading the code, the situation is more complex than it first appeared. The line you reference is not used when loading from a file or input stream. (Just from a string, i believe).  

When a Table is read, a Source object is created. The source object has a number of constructors, some accept a charset and some do not. 

(Aside: For some reason the constructor that takes a reader has no variation with a Charset argument. This is set in the CsvReader code you highlighted. It seems like there could be two constructors for Readers, one that takes a charset and the other that doesn't and the charset determination might be handled in the former, rather than in the CsvReader. This design would make Sources based on reader more like those based on File and InputStream, but I'm probably missing something).

When a File is read without a Charset, the source object attempts to determine the charset used to write the file. It does this using a class called CharsetDetector, from the IBM ICU library. This can be hit-or-miss, since there's no deterministic way to do it. A file may have too few bytes for this to work, for example. If this fails, ONLY THEN is the default charset used. 

It seems like the API for reading from URLs has variations that accept a charset as well, but they don't use the ReadOptions mechanism. 

(Another aside, I recently had a CSV file created using Excel's save-as CSV with UTF-8 encoding. On reading and writing this data from Tablesaw, some characters were not written properly. My assumption is that the CharacterDetecter picked the wrong Charset - Maybe UTF-16?)

**Comment by benmccann** [comment]
I sent a PR to fix this (https://github.com/jtablesaw/tablesaw/pull/879). I think you also need changes to your `Scratch` class. Encoding is a pain :stuck_out_tongue: 

```
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.nio.charset.Charset;

import tech.tablesaw.api.Table;
import tech.tablesaw.io.csv.CsvReadOptions;

class Scratch {
    public static void main(String[] args) throws IOException {
        System.out.println(Charset.defaultCharset());
        
        InputStreamReader reader = new InputStreamReader(new ByteArrayInputStream("колонка_А,колонка_Б,колонка_В".getBytes("UTF-8")), "UTF-8"); // cyrillic
        CsvReadOptions options = CsvReadOptions.builder(reader).header(false).build();
        Table dataset = Table.read().usingOptions(options);

        PrintStream out = new PrintStream(System.out, true, "UTF-8");
        out.println("2: " + dataset.getString(0, 0));
    }
}
```

**Comment by lwhite1** [comment]
I'm closing as fixed. @DrIgor If the solution doesn't meet your needs please lmk.
