### ISSUE TITLE
Using stream().parallel()

### ISSUE THREAD

**Issue by trago** [jtablesaw/tablesaw#841]
When using this approach for filtering or traversing rows to update, it has problems, I assume concurrence problems. For example, copying from one table to other gives unexpected results.

It is possible to have parallel working?

Thanks

**Comment by lwhite1** [comment]
Tablesaw is not thread safe, by design. To make it thread safe would be much harder and probably quite a bit slower. It is really designed for a single user doing data analysis.

FWIW, it wouldn't make much difference in this case, probably, but if you want people to address your concerns, it would be best to provide more details about what you were doing, what you expected, and what went wrong.
