### ISSUE TITLE
Scala interopability: overload function cannot be matched - question

### ISSUE THREAD

**Issue by hmf** [jtablesaw/tablesaw#859]
I am using tablesaw from Scala. When I called:

```scala
    val cx: FloatColumn = FloatColumn.create("X", Array(1.0f, 2.0f))
```
compilation failed stating that a valid type match was not found. In the [ensuing discussion](https://users.scala-lang.org/t/overload-not-found-when-using-java-library-with-float-how-to-circumvent/7016/5) someone noticed that the [parameter to the call](https://github.com/jtablesaw/tablesaw/blob/v0.38.1/core/src/main/java/tech/tablesaw/api/FloatColumn.java#L53):

```scala
public static FloatColumn create(String name, Float[] arr)
```
uses an array of boxed Float and its not what I expected, which is an unboxed array `float[]`. I am using this to work on data that is in its unboxed form. This means that conversions take up CPU and memory. So I have two questions:

* What is the reason for using boxed floats?
* It seems like Java varargs are unboxed arrays. Was this used purposely to cover the unboxed values? I assume the values are then boxed.

TIA

**Comment by lwhite1** [comment]
Unfortunately, we don't support Scala since none of us uses it, AFAIK. 

In Java that you can create a column with a collection argument that uses boxed values, but there is also a method that uses a primitive array. The boxed value approach allows us to provide an API that supports the standard collections framework.
