### ISSUE TITLE
Make data field visible in DataColumns for extending classes

### ISSUE THREAD

**Issue by jechaviz** [jtablesaw/tablesaw#888]
For example, In DoubleColumn data field is private, so we can't modify to remove elements, also there's no get method to get it. There're useful methods in DoubleArrayList class that are not usable because the data field is private.

To do a workaround I'm doing this: 
`data=new DoubleArrayList(asDoubleArray()); `
but it's not nice. It would be simpler if it would be protected, so the simplest solution would be to change this:

`private final DoubleArrayList data;`
to
`protected DoubleArrayList data;`

Thank you

**Comment by jechaviz** [comment]
In fact, what I want is to keep a fixed-sized pushing a new value to the column and then removing first if a `maxSize` field is set in my extended class. It's to memory handling, because I'm feeding a column with a stream, and I need to remove older values, and only keep `maxSize` new values in memory.

**Comment by lwhite1** [comment]
Tablesaw isn't really designed well for that kind of use-case. You have to move all the values in the array every time you update one value. It would be very expensive. 

The data object is private because it's an implementation detail. I have never tried to subclass a column. I would be surprised if it were easy - or even possible - to do.

**Comment by lwhite1** [comment]
Made them protected
