### ISSUE TITLE
How to modify a value in a table

### ISSUE THREAD

**Issue by huangshanqishi** [jtablesaw/tablesaw#893]
What method is used to modify the value in the third row and fourth column？

**Comment by lwhite1** [comment]
it depends on the type of the column.

Since java uses zero-based indexing, you can use something like this:

      myTable.stringColumn(3).set(2, "foo");

If you have to modify many rows, it's best to get a row object:

     for (Row row: myTable) { row.setString(3, "foo");}

That would loop over all the rows, setting the value of the fourth column
to "foo" in every row.

**Comment by lwhite1** [comment]
it depends on the type of the column.

Since java uses zero-based indexing, you can use something like this:

      myTable.stringColumn(3).set(2, "foo");

If you have to modify many rows, it's best to get a row object:

`    
     for (Row row: myTable) { row.setString(3, "foo");}
`

That would loop over all the rows, setting the value of the fourth column
to "foo" in every row.

In general, I almost always refer to columns by their name, rather than by their number, so I would probably write:

`     for (Row row: myTable) { row.setString("myColumn", "foo");}
`

**Comment by lwhite1** [comment]
closing
