### ISSUE TITLE
Provide a `Table.setColumnNames(String[] names)` method

### ISSUE THREAD

**Issue by multimeric** [jtablesaw/tablesaw#923]
Currently if you read in a CSV without a header, you end up with a table with names that are `C0, C1, C2` etc. If you are in a situation were you know what these columns should be called, it would be ideal to be able to set the column names, e.g. 

```java
Table t1 = Table.read().usingOptions(options);
t1.setColumnNames({"A", "B", "C"})
```

**Comment by benmccann** [comment]
You can rename the columns after reading the table

**Comment by multimeric** [comment]
I'm not saying this isn't possible, just that it's inconvenient that you need to set each column name individually. I'm happy to write a PR if you agree, I'm just running it by you guys first.

**Comment by benmccann** [comment]
I imagine it shouldn't be too hard. Probably something like `table.columns.stream().forEach((c, i) -> c.setName(names[i]))`. The problem with adding new APIs is that it becomes very difficult to know what's possible because there end up being too many too keep them all straight. It's better to add the building blocks to let you do anything you want without too much difficulty. There are too many use cases to solve all of them directly in the API

**Comment by multimeric** [comment]
It's true, a simple `forEach` should be sufficient. Although one way to think of my proposed function is as like the "setter" property for the "getter", which is [`columnNames()`](https://www.javadoc.io/static/tech.tablesaw/tablesaw-core/0.38.2/tech/tablesaw/api/Table.html#columnNames--). I think it makes sense that, if we can retrieve this list of strings, we can also set them in the same way.
