### ISSUE TITLE
misunderstood on StringColumn#asDoubleColumn

### ISSUE THREAD

**Issue by alex-fu** [jtablesaw/tablesaw#954]
Hi,

I was misunderstood on StringColumn#asDoubleColumn today. I thought it will convert string to double, but when I test it I found it turns out to be the index of value set. So why it was designed like this? It was really confusing me.

I suggest the implementation should be trying to convert string to double, and set to NaN if conversion failed. 

https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/api/StringColumn.java#L372

**Comment by benmccann** [comment]
I'd expect it to convert string to double as well

**Comment by alex-fu** [comment]
Great! I'll submit a PR later.

**Comment by lwhite1** [comment]
I believe it was designed that way. 
IIRC, all the columns can be converted to DoubleColumn (e.g. DateColumn.asDoubleColumn). Again, IIRC, the intent was to have a numeric value that could be used in Smile to represent categorical data in ML code that didn't handle arbitrary Objects, only numbers. Using the numbers that represent the strings in the dictionary works well in that sense, since you get a unique value for each unique string.

If you have a StringColumn that contains a stringified doubles, you can use the mapInto() method to do the conversion.
