### ISSUE TITLE
Column type conversion

### ISSUE THREAD

**Issue by eric-liuyd** [jtablesaw/tablesaw#985]
I am wondering how to convert column type (e.g. from StringColumn to DoubleColumn) ?
Assuming a table (called `df` ) with one column named "ratio", and the values are all strings of double like "0.3", "1.0", "0.9", etc. So it is a StringColumn. Now I simply want to convert the column to a DoubleColumn (so it will be with values like 0.3, 1.0, 0.9, etc.). But I couldn't find any available methods in doc and source code. 

I tried to write a long piece of code. It works but still very long. Besides, it is not an optimal solution since it generate a new column "new_ratio" but not convert the values in-place.

`df.addColumns(df.column("ratio").asStringColumn().mapInto(
 x -> Double.parseDouble(x), DoubleColumn.create("new_ratio", new double[df.rowCount()]))`

**Comment by lwhite1** [comment]
StringColumn implements a method:

    DoubleColumn parseDouble()

You can't convert the column in place. You can, however, replace the original using.

   

      df.replaceColumn("myStringColName", 
           df.stringColumn("myStringColName").parseDouble().setName("myStringColName"));

It's long because it's doing three things, creating a new column that holds Doubles, replacing the original with the new column in the table, and changing the name of the new column to match the old column.
